### ISSUE TITLE
Action-Specific Model path

### ISSUE THREAD

**Issue by yolo615** [Silverster98/HUMANISE#10]
I ran the evaluation script as the following but got very poor results. The avatar is just flying with meaningless motions. Is there any extra parameters setting or anything I have missed?
`bash scripts/eval.sh 20220829_194320 "walk"`

https://user-images.githubusercontent.com/45808830/217264546-52f390ce-f5fb-4316-b63d-eb5cd25612ba.mp4

**Comment by Silverster98** [comment]
The result seems abnormal. How about sampling more results? Do all results have such behavior?

**Comment by Silverster98** [comment]
Here is one of my results generated with this scene.
![motion](https://user-images.githubusercontent.com/34436920/217408856-11d82fe4-d812-415f-8149-ee2ca673be6f.gif)

**Comment by yolo615** [comment]
Thanks a lot. I found that this was because I set the wrong Action-Specific Model path. When I fixed this error, the avatar's actions became normal. 

By the way, when I test the 'sit' model, I generate 10 samples, but none of them sit in the right position. Is this normal?



![motion](https://user-images.githubusercontent.com/45808830/217423838-ce3f6986-ce1c-4c8b-b5e3-ad45eb6d583c.gif)

**Comment by Silverster98** [comment]
I think it is normal, it is very hard to generate physically plausible results. First, accurately grounding the target object in a 3D scene is really challenging. Second, fine-grained 3D geometry awareness has not been well studied. Both two challenges make it hard to align the motion with the target interacting object. Let alone we solving this problem with a cVAE-based generative model in an end-to-end manner. We hope that the community can pay more attention to this field and push it forward.

**Comment by ruizhao1997** [comment]
Thanks for your reply. When will the Action-Agnostic Model be released? 
Is the Action-Specific Model just overfit on one specific action and ignores the input text? Because whatever the text is, the model will generate the same action.

**Comment by Silverster98** [comment]
We will release that soon.

**Comment by Silverster98** [comment]
I have released the code for action-agnostic model just now. I will close this issue. If you have any other questions, just open a new issue.
