### ISSUE TITLE
{scene_id}_vh_clean_2.ply doesn't have field of name label

### ISSUE THREAD

**Issue by F1y1113** [Silverster98/HUMANISE#12]
Hi, I was running your script **align_motion.py** for aligning the motions with scenes, and seems that in this line **labels[:] = plydata['vertex'].data['label']**, you use property 'label' from **{scene_id}_vh_clean_2.ply**. 
However, I cannot find 'label' under the ply file.
Looking forward to your reply!

**Comment by Silverster98** [comment]
Apologies for the delayed response. I want to mention that I'm utilizing `{scene_id}_vh_clean_2.labels.ply` instead of `{scene_id}_vh_clean_2.ply`.

Please refer to https://github.com/Silverster98/HUMANISE/blob/78362f472d6174faf27e13699ebf5c3da869f2b5/dataset/align_motion.py#L1953.

**Comment by F1y1113** [comment]
Thanks for replying! I wonder how do I obtain this 00_vh_clean_2.lables.ply? The ply files from scannet don't have labels.

**Comment by Silverster98** [comment]
I have checked the download script of ScanNet. The file type contains the `_vh_clean_2.labels.ply`. You can recheck the official download script.

```python
FILETYPES = ['.aggregation.json', '.sens', '.txt', '_vh_clean.ply', '_vh_clean_2.0.010000.segs.json', '_vh_clean_2.ply', '_vh_clean.segs.json', '_vh_clean.aggregation.json', '_vh_clean_2.labels.ply', '_2d-instance.zip', '_2d-instance-filt.zip', '_2d-label.zip', '_2d-label-filt.zip']
```

**Comment by F1y1113** [comment]
Gotcha! Thank you

**Comment by siddharthKatageri** [comment]
Hi @F1y1113 
As you are trying to synthesize your own dataset, were you able to download the Scan2Cad dataset's ```full_annotation.json```?
If you have it, can you please share it with me?
My email id is siddharth.katageri@research.iiit.ac.in.
