### ISSUE TITLE
Extract motion segments from AMASS with BABEL

### ISSUE THREAD

**Issue by siddharthKatageri** [Silverster98/HUMANISE#14]
Hi @Silverster98,
I was running ```python dataset/babel_process.py --action "walk"``` for extracting ```walk``` motion segments. The total segments that I get, irrespective of time duration, is 6345. And the selected motions between the time range of 1sec to 4sec are 3844.
However, in the dataset which you provide, the ```pure_motion``` for ```walk``` has only 777 motion segments. 
1. What is the time duration you set for humanise dataset? Is it 1sec to 4sec itself?
2. Do you perform any human/automatic checks to remove motion segments having inconsistent walk motion (as babels annotations have some error) to go from 3844 to 777?

Thanks!

**Comment by Silverster98** [comment]
1. We set the time duration from 1 sec to 4 sec.
2. I have checked the git history, but I really forget how I remove so much the motion segments of the walk action. But I do remove some inconsistent motion segments by human check. (I guess that I randomly selected a subset of these walk segments for balancing the number of different actions in our earlier experiments.) You can re-synthesize human-scene interactions of the walk action with these walk segments if you want.

I'm sorry for the confusion.

**Comment by siddharthKatageri** [comment]
Thanks a lot for your quick reply!
1. I was trying to re-synthesize human-scene interaction for walk action with your provided ```pure_motion```. 
I run,
```PYOPENGL_PLATFORM=egl python dataset/align_motion.py --anno_path=./align_data_testing/ --action="walk" --max_s=1 --use_lang --sort_scene --save --rendering```
I was expecting the same ```scene_motion``` pairs as in your provided ```align_data_release```. But that is not the case. For example, for me the first motion ```005646_5cff77ab-812f-4a37-a310-2f2cd4000f30``` is paired with ```scene0000```, and in your align_data_release the motion ```005646_5cff77ab-812f-4a37-a310-2f2cd4000f30``` is paired with ```scene0367``` and ```scene0677```.
I tried turning off the sorting of scenes, but even that does not give the same pairs.
2. Getting different pairs is okay, but I am not sure if the generated human-scene interaction would be correct, as rendering to check its correctness takes a lot of time. Can you suggest something to decrease the rendering time (gpu)?
3. According to your experience, if a new set of HSI is synthesized for walk, are babel annotations too erroneous to include manual checking to remove invalid HSI? 
4. Also was curious about, [Here](https://github.com/Silverster98/HUMANISE/blob/78362f472d6174faf27e13699ebf5c3da869f2b5/dataset/align_motion.py#L1942) how are you finding if a motion is invalid.

Thanks!

**Comment by Silverster98** [comment]
1.It is because the motions are totally unordered when they are loaded by `glob`. If you want to re-synthesize the interactions, I think you can exclude the motions that have been used in `align_data_release` and just align the unused motions.

2.The rendering itself is time-consuming. I use `pyrender` in the implementation with [`egl`](https://pyrender.readthedocs.io/en/latest/examples/offscreen.html), which allows for GPU-accelerated rendering without a display manager; maybe you can use some other faster libraries.

3, 4.I remember that there are not too many inaccurate motions for walk action; I just removed some unreasonable motions, such as marching in place.

Thanks!
