### ISSUE TITLE
ModuleNotFoundError: No module named 'pointops_cuda'

### ISSUE THREAD

**Issue by daidaiershidi** [Silverster98/HUMANISE#15]
Hello,

I am having an error when executing : bash scripts/train.sh sit
```
  File "./project/HUMANISE/model/pointtransformer/pointops.py", line 7, in <module>
    import pointops_cuda
ModuleNotFoundError: No module named 'pointops_cuda'
```
And I find the same error in https://github.com/POSTECH-CVLab/point-transformer/issues/27

But when I found the file in ./miniconda3 (like `find ./miniconda3/ -name "pointops*"`), I realized that I don't have this file at all.

**Comment by Silverster98** [comment]
Did you install the `pointops` by executing the following commands in https://github.com/POSTECH-CVLab/point-transformer/blob/master/env_setup.sh#L20C5-L21C29?

**Comment by Silverster98** [comment]
I have copied the `pointops` into my [repo](https://github.com/Silverster98/pointops); you can install it by directly running `pip install "git+https://github.com/Silverster98/pointops"`

**Comment by daidaiershidi** [comment]
> I have copied the `pointops` into my [repo](https://github.com/Silverster98/pointops); you can install it by directly running `pip install "git+https://github.com/Silverster98/pointops"`

Thank you very much. I just solved this problem this morning because I was having some problems with my machine.
The other problem I had was that when I downloaded the


1. [ScanNet V2](http://www.scan-net.org/) Dataset
2. Our pre-synthesized [data](https://docs.google.com/forms/d/e/1FAIpQLSfzhj2wrRLqAXFVOTn8K5NDN-J_5HueRTohMAlayqBuPPWA1w/viewform?usp=sf_link), or you can generate your own data with our pipeline)
3. [SMPLX v1.1](https://smpl-x.is.tue.mpg.de/download.php)


where is the path of 'preprocess_scene_folder'

**Comment by Silverster98** [comment]
> 

Following [link](https://github.com/daveredrum/Pointnet2.ScanNet#preprocess-scannet-scenes) to preprocess the ScanNet scenes; then change the preprocess_scene_folder configuration in utils/configuration.py.
