### ISSUE TITLE
Auxiliary loss

### ISSUE THREAD

**Issue by Dean-UQ** [Silverster98/HUMANISE#18]
Hi Wang,
  I noticed that you defined an action recognition loss as one of the auxiliary losses in the paper. However, I did not find this loss in the code([ return ground_loss, rec_trans_loss, rec_orient_loss, rec_body_pose_loss, rec_body_mesh_loss, kl_loss](https://github.com/Silverster98/HUMANISE/blob/11dee60fb8e76824bb55d1340036a5b739e3480b/model/solver.py#L258)). May be I did not find it?
 
Thx

**Comment by Silverster98** [comment]
The action recognition loss is used in the `Action-Agnostic` model, please check out the `agnostic` [branch](https://github.com/Silverster98/HUMANISE/tree/agnostic).
