### ISSUE TITLE
About align my own motion data with HUMANISE setting

### ISSUE THREAD

**Issue by Diouo** [Silverster98/HUMANISE#20]
Wang, it is really a great work on this project! I’m new to it and I would like to compare HUMANISE with my work in my paper.
However, I am not sure how to align my motion data, which is generated by my motion diffusion model, with your setting. Specifically, I don't know how to align the **Coordinate System** of my motion with HUMANISE. if I use visualize_dataset.py with my motion data directly, the motion data I generated will have the wrong initial orientation in visualization . 
Thus, could you provide me with the detail about the motion **Coordinate System** of HUMANISE? I would appreciate it. 

https://github.com/Silverster98/HUMANISE/assets/34906791/2f037097-00a5-4fe2-a1ff-2ff69d2c1101

**Comment by Diouo** [comment]
![Uploading Screenshot (7)(1).png…]()

**Comment by Diouo** [comment]
![Screenshot (7)(1)](https://github.com/Silverster98/HUMANISE/assets/34906791/f794089b-121d-4ebe-978e-dad7feeb3740)

**Comment by Silverster98** [comment]
> Wang, it is really a great work on this project! I’m new to it and I would like to compare HUMANISE with my work in my paper. However, I am not sure how to align my motion data, which is generated by my motion diffusion model, with your setting. Specifically, I don't know how to align the **Coordinate System** of my motion with HUMANISE. if I use visualize_dataset.py with my motion data directly, the motion data I generated will have the wrong initial orientation in visualization . Thus, could you provide me with the detail about the motion **Coordinate System** of HUMANISE? I would appreciate it.
> 
>  My.mp4

My coordinate system uses the z-axis as the up-axis, and the height of the scene floor is nearly as same as the xy plane (i.e., the height is nearly zero).

**Comment by Diouo** [comment]
> > Wang, it is really a great work on this project! I’m new to it and I would like to compare HUMANISE with my work in my paper. However, I am not sure how to align my motion data, which is generated by my motion diffusion model, with your setting. Specifically, I don't know how to align the **Coordinate System** of my motion with HUMANISE. if I use visualize_dataset.py with my motion data directly, the motion data I generated will have the wrong initial orientation in visualization . Thus, could you provide me with the detail about the motion **Coordinate System** of HUMANISE? I would appreciate it.
> > My.mp4
> 
> My coordinate system uses the z-axis as the up-axis, and the height of the scene floor is nearly as same as the xy plane (i.e., the height is nearly zero).

Wang, thank you for your help! I appreciate your quick response. The issue is now resolved. 😊
