### ISSUE TITLE
The code implementation for more actions

### ISSUE THREAD

**Issue by ZJHTerry18** [Silverster98/HUMANISE#21]
Hi! In your paper, you showed some examples of generalizing to 'jump up', 'turn to', 'open' and 'place' motions. I wonder if you can provide the code of generating these types of motions? Because in `data/align_motion.py` (line 1798-1808), I only find support of the 4 default actions:
```python
## sample valid position and rotation according to sit action
        if action == 'sit':
            action_align = SitAlign(self.annotations, self.instance_to_semantic, self.label_mapping, scene_path, static_scene, static_scene_label, translate_mat, body_vertices, joints_traj)
        elif action == 'stand up':
            action_align = StandUpAlign(self.annotations, self.instance_to_semantic, self.label_mapping, scene_path, static_scene, static_scene_label, translate_mat, body_vertices, joints_traj)
        elif action == 'walk':
            action_align = WalkAlign(self.annotations, self.instance_to_semantic, self.label_mapping, scene_path, static_scene, static_scene_label, translate_mat, body_vertices, joints_traj)
        elif action =='lie':
            action_align = LieAlign(self.annotations, self.instance_to_semantic, self.label_mapping, scene_path, static_scene, static_scene_label, translate_mat, body_vertices, joints_traj)
        else:
            raise Exception('Unsupport action: {}'.format(action))
``` 
Thanks!

**Comment by Silverster98** [comment]
> Hi! In your paper, you showed some examples of generalizing to 'jump up', 'turn to', 'open' and 'place' motions. I wonder if you can provide the code of generating these types of motions? Because in `data/align_motion.py` (line 1798-1808), I only find support of the 4 default actions:
> 
> ```python
> ## sample valid position and rotation according to sit action
>         if action == 'sit':
>             action_align = SitAlign(self.annotations, self.instance_to_semantic, self.label_mapping, scene_path, static_scene, static_scene_label, translate_mat, body_vertices, joints_traj)
>         elif action == 'stand up':
>             action_align = StandUpAlign(self.annotations, self.instance_to_semantic, self.label_mapping, scene_path, static_scene, static_scene_label, translate_mat, body_vertices, joints_traj)
>         elif action == 'walk':
>             action_align = WalkAlign(self.annotations, self.instance_to_semantic, self.label_mapping, scene_path, static_scene, static_scene_label, translate_mat, body_vertices, joints_traj)
>         elif action =='lie':
>             action_align = LieAlign(self.annotations, self.instance_to_semantic, self.label_mapping, scene_path, static_scene, static_scene_label, translate_mat, body_vertices, joints_traj)
>         else:
>             raise Exception('Unsupport action: {}'.format(action))
> ```
> 
> Thanks!

Sorry, these codes are not merged into my repository. I can't find them now.
