### ISSUE TITLE
side-view visualizations

### ISSUE THREAD

**Issue by Dean-UQ** [Silverster98/HUMANISE#22]
Hi,

  Nice work, I would like to visualize synthesized human motion samples in their side-view videos. Which parameters in the visualization module should be tuned?   
﻿
Thanks

**Comment by Silverster98** [comment]
> Hi,
> 
> Nice work, I would like to visualize synthesized human motion samples in their side-view videos. Which parameters in the visualization module should be tuned? ﻿ Thanks

You should change the camera pose. Please refer to https://github.com/Silverster98/HUMANISE/blob/main/utils/visualization.py and find the `camera_pose` parameters.

**Comment by Dean-UQ** [comment]
Thanks,  I find the camera_pose parameters. If I want to visualize side-view videos, what hyperparameters should I set  `camera_pose` to?

**Comment by Silverster98** [comment]
> Thanks, I find the camera_pose parameters. If I want to visualize side-view videos, what hyperparameters should I set `camera_pose` to?

You can set the camera pose (or camera pose trajectory) heuristically based on the motion trajectory, making the camera target the motion. However, due to the existence of the 3D scene, the camera may be occluded by the scene. That's why we choose a top-down view instead of a side-view.

**Comment by Silverster98** [comment]
I will close this issue; if you have any more questions, please re-open it.
