### ISSUE TITLE
Issue with Aligning Motion and Temporal Inconsistency in HUMANISE Dataset

### ISSUE THREAD

**Issue by T1-Edward** [Silverster98/HUMANISE#23]
Dear researchers,

Regarding the HUMANISE dataset, we encountered two issues during usage:

1. What do the terms "scene translation" and "translation" in align motion mean, and how should they be used? For an align motion, we added the "scene translation" to the coordinates of each point in the scene from ScanNet. We also added the "translation" to each frame of the corresponding pure motion in the align motion, expecting to achieve alignment. However, we found that the pure motion of the character does not align with the scene, and the position of the character in the scene does not match the reference .mp4 and .gif provided by HUMANISE. We also tried using the `apply_translation()` function from the trimesh library but did not achieve the expected results.

2. While visualizing the pure motion of this align motion frame by frame in MeshLab, we noticed that the person is at the starting position in frame 0, close to the door in frame 25, almost at the door in frame 35, but in frame 43 (the last frame), the person has moved back to a position earlier than frame 25. Upon reviewing the corresponding .mp4 and .gif, we observed that there was no apparent backward walking. Therefore, we find this inconsistency in the temporal sequence puzzling and are reaching out for clarification. Note: The align motion we visualized is:
{'action': 'walk', 'motion': '007071_7adc87a5-ee76-4e09-9cc3-ab766f2022bb', 'scene': 'scene0007_00', 'scene_translation': TrackedArray([-4.22165146, -1.67899775, -0.07502296]), 'translation': array([ 1.6910821 , -0.20508415, -0.05157547], dtype=float32), 'rotation': 2.2689280275926285, 'utterance': 'walk to the door', 'object_id': 5, 'object_label': 'door', 'object_semantic_label': 8}

Additionally, as shown in the attached image, we have already applied the 'scene translation' to the scene and input the 'orient' and 'trans' of the human body into the SMPL-X model. We also used the 'rotation' from the anno.pkl (align motion), but we are unsure how to use the 'translation' from the anno.pkl (align motion) to make the person lie on the bed, in order to complete the alignment between the motion and the scene. The align motion associated with this image is the one with motion_id=0 in the annotation.csv, and its anno.pkl content is:
[{'action': 'lie', 'motion': '000122_b9fa1c75-98e9-4be4-91d7-6af4fc4275ad',
'scene': 'scene0000_00', 'scene_translation': TrackedArray([-4.11121502, -4.17789347, -0.06122726]), 'translation': array([ 0.79074603, -2.3111258 , 0.7164987 ], dtype=float32), 'rotation': 5.585053606381854, 'utterance': 'lie on the bed', 'object_id': 37, 'object_label': 'bed', 'object_semantic_label': 4}]

We would appreciate your response. Thank you!

![lie_motion_id0](https://github.com/user-attachments/assets/87860b9a-a4a0-48f9-9cd3-fa2fc91f1537)

**Comment by Silverster98** [comment]
Hi,

Are these visualization results produced by your own scripts? Have you tried our [visualization script](https://github.com/Silverster98/HUMANISE/blob/main/visualize_dataset.py)? Are the results right? 
﻿
For the first issue, the "scene translation" transforms the ScanNet scene to coordinate origin. "translation" and "rotation" in `anno.pkl` transform the original AMASS motion sequence to align with the "transformed" scene. You can check the visualization code in [Line83](https://github.com/Silverster98/HUMANISE/blob/main/visualize_dataset.py#L83) and [Line90~91](https://github.com/Silverster98/HUMANISE/blob/main/visualize_dataset.py#L90-L91).  **Notably, You cannot directly transform the body mesh using "translation" and "rotation"! These two parameters are specific to SMPL-X parameters. That means transforming the SMPL-X parameters is not equal to transforming the corresponding mesh. Please check [this function](https://github.com/Silverster98/HUMANISE/blob/main/visualize_dataset.py#L15).**
﻿
For the second issue, can you provide more details, including the visualization results rendered from your script and ours? You can also post your code here, and I can help you diagnose it.

**Comment by xiaochy** [comment]
Dear researchers, 
  We have solved those two problems by following your guidance. Thank you a lot for your reply! Wish you a great day!

**Comment by T1-Edward** [comment]
Dear researchers,

We have solved these two problems by following your guidance. 
Thanks a lot for your patient and timely reply! 

Best wishes
