### ISSUE TITLE
ScanNet V2 dataset

### ISSUE THREAD

**Issue by xljh0520** [Silverster98/HUMANISE#3]
Thanks for sharing your code. I notice that you mention ScanNet V2 dataset in Data Preparation. Do I need to download the whole ScanNet V2 dataset to train my model in your HUMANISE dataset?

**Comment by Silverster98** [comment]
We use the [code](https://github.com/daveredrum/Pointnet2.ScanNet/blob/master/preprocessing/collect_scannet_scenes.py) to preprocess the scenes, the code only uses the following files: `${scene_id}_vh_clean_2.0.010000.segs.json`, `${scene_id}.aggregation.json`, `${scene_id}_vh_clean_2.ply`. So you don't need to download the whole dataset.
