### ISSUE TITLE
Quantitative Evaluation

### ISSUE THREAD

**Issue by xljh0520** [Silverster98/HUMANISE#4]
Hi, I run the following command the eval the model.
```
bash scripts/eval_metric.sh 20220829_194320 "walk"
```
I get a file named *recon.json* in the folder, and I have a few questions.
1. How could I get another *generation.json* with generation metrics?
2. How could I reproduce table2 in your paper?

**Comment by Silverster98** [comment]
1. Set `eval_rec=False` in [`eval_metric_motion.py`](https://github.com/Silverster98/HUMANISE/blob/main/eval_metric_motion.py#L64) to compute generation metrics (only `goal dist.`). It will take several hours to compute the results.
2. For APD, we will release the code later. `quality score` and `action score` are computed by perceptual study.
