### ISSUE TITLE
GPU resource in training

### ISSUE THREAD

**Issue by xljh0520** [Silverster98/HUMANISE#5]
Hi, I noticed that you mentioned you use a V100 GPU with batch size of 32 in training. However, I found it's hard to set batch size of 32 with a single V100 GPU. Could you tell me more detail about your environment and training?

**Comment by Silverster98** [comment]
I forgot whether our GPU is A100 or V100. But I remember that it has 80G memory size. So it enables the training with 32 batch size. You can decrease the batch size if your GPU has no such big memory size.
