### ISSUE TITLE
Code release for APD metric

### ISSUE THREAD

**Issue by Dai-Wenxun** [Silverster98/HUMANISE#6]
Hi, bro!
When do you prepare to release the code for APD evaluation? Thank you!

**Comment by Silverster98** [comment]
I'm sorry for not getting back to you sooner. We have updated the repo and released the code for APD computation. Please check out the [readme](https://github.com/Silverster98/HUMANISE#action-specific-model).

Please feel free to ask me if you have any other questions.

**Comment by Dai-Wenxun** [comment]
谢谢赞哥！
