### ISSUE TITLE
How to render different view demo？

### ISSUE THREAD

**Issue by xljh0520** [Silverster98/HUMANISE#7]
Hi, I noticed that you use fixed top-down view to visualize the results [here](https://github.com/Silverster98/HUMANISE/blob/main/utils/visualization.py#L167). How could I modify the camera pose to get another view visualization such as looking form one corner of the room?

**Comment by Silverster98** [comment]
I think this is difficult because it is challenging to locate the corner of the room or find a proper view direction. That is why I directly use a top-down view, which can capture the whole scene and is easy to set up.

You can manually set a proper view direction for each scene. But it will be time-consuming and laborious.

**Comment by xljh0520** [comment]
Thanks for your reply! I try to visualize what the man see in the motion sequence, and I locate the eyes of the man.  How could I adjust the camera pose [here](https://github.com/Silverster98/HUMANISE/blob/main/utils/visualization.py#L167) to get a proper view direction?

**Comment by Silverster98** [comment]
If you want to set the camera at the eyes of the man, you need to compute a transformation matrix to transform the initial camera pose into such a final pose. The final position can be the coordinates of the eyes and the final view direction can be the normal direction of the eyes. Then you can compute the transformation with the initial pose and final pose. You can use this transformation as the input of the [Scene.add](https://pyrender.readthedocs.io/en/latest/generated/pyrender.Scene.html#pyrender.Scene.add) method.

**Comment by xljh0520** [comment]
Thanks for your reply! It helps me a lot. But, I still have another question aoubt the  transformation matrix you mentioned. Does the transformation matrix equal to the camera extrinsics that transform the world coordinate system to camera coordinate system? I get the coordinates of the eyes and view direction to calculate  camera extrinsics as camera pose in the code. However, the results are wrong.

**Comment by Silverster98** [comment]
I don't think it is the camera extrinsics. In pyrender, the initial camera view direction is the negative direction of z-axis, see [Creating Cameras](https://pyrender.readthedocs.io/en/latest/examples/cameras.html). We can denote the view direction as $v_i = [0, 0, -1]$ and denote the target view direction as $v_t$. Then, we can compute a rotation matrix $R$ with $v_i$ and $v_t$. The initial position of the camera is the coordinate origin and we can compute a translation vector $T$ with the target camera position. I think the camera pose is formed by $R$ and $T$.

**Comment by xljh0520** [comment]
Sorry to bother you again. Translation vector $T$ is easy to obtain by calculating difference between two coordinates. But, I'm a little confused with the rotation matrix $R$ you mentioned. I think there are more than one rotation matrix $R$  between $v_{i}$ and $v_{b}$. Do I need another vector to get the uqique $R$?

**Comment by Silverster98** [comment]
Use [Rodrigues' rotation formula](https://en.wikipedia.org/wiki/Rodrigues'_rotation_formula), refer to [this](https://math.stackexchange.com/questions/180418/calculate-rotation-matrix-to-align-vector-a-to-vector-b-in-3d) for moe details. I have implemented this [here](https://github.com/Silverster98/HUMANISE/blob/main/utils/geo_utils.py#L84) in this repo.

Remember to rotate first and then translate.

**Comment by Silverster98** [comment]
I will close this issue. If you have any other questions, feel free to open a new issue.
