### ISSUE TITLE
Please feel free to create issues if you have any questions!

### ISSUE THREAD

**Issue by Silverster98** [Silverster98/HUMANISE#8]

**Comment by myy888** [comment]
hi. I have question about parameter “orient" ,why the dimension of this parameter is 6?

**Comment by Silverster98** [comment]
> hi. I have question about parameter “orient" ,why the dimension of this parameter is 6?

We use the 6D representation; please refer to https://github.com/Silverster98/HUMANISE/blob/main/model/dataloader.py#L311.
